"use strict";(self.webpackChunk_ant_design_pro_editor=self.webpackChunk_ant_design_pro_editor||[]).push([[1756],{16283:function(o,n,e){e.r(n),e.d(n,{demos:function(){return s}});var a=e(90228),r=e.n(a),u=e(87999),p=e.n(u),d=e(75271),i=e(10549),I=e(94283),s={"freecanvas-demo-basic":{component:d.memo(d.lazy(function(){return e.e(7673).then(e.bind(e,20253))})),asset:{type:"BLOCK",id:"freecanvas-demo-basic",refAtomIds:["FreeCanvas"],dependencies:{"index.tsx":{type:"FILE",value:e(84672).Z},"@ant-design/pro-editor":{type:"NPM",value:"1.2.1"},antd:{type:"NPM",value:"5.12.8"}},entry:"index.tsx"},context:{"@ant-design/pro-editor":i,antd:I},renderOpts:{compile:function(){var c=p()(r()().mark(function _(){var l,m=arguments;return r()().wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,e.e(6495).then(e.bind(e,86495));case 2:return t.abrupt("return",(l=t.sent).default.apply(l,m));case 3:case"end":return t.stop()}},_)}));function v(){return c.apply(this,arguments)}return v}()}}}},51043:function(o,n,e){e.r(n),e.d(n,{texts:function(){return a}});const a=[{value:"A free canvas encapsulation based on ",paraId:0,tocIndex:0},{value:"ReactFlow",paraId:0,tocIndex:0},{value:"Property",paraId:1,tocIndex:3},{value:"Type",paraId:1,tocIndex:3},{value:"Description",paraId:1,tocIndex:3},{value:"children",paraId:1,tocIndex:3},{value:"ReactNode",paraId:1,tocIndex:3},{value:"The child elements of the free canvas component",paraId:1,tocIndex:3},{value:"viewport",paraId:1,tocIndex:3},{value:"Viewport",paraId:1,tocIndex:3},{value:"The initial value of the viewport",paraId:1,tocIndex:3},{value:"defaultViewport",paraId:1,tocIndex:3},{value:"Viewport",paraId:1,tocIndex:3},{value:"The default value of the viewport",paraId:1,tocIndex:3},{value:"control",paraId:1,tocIndex:3},{value:"boolean",paraId:1,tocIndex:3},{value:"Whether to display the control panel",paraId:1,tocIndex:3},{value:"onViewportChange",paraId:1,tocIndex:3},{value:"(viewport: Viewport) => void",paraId:1,tocIndex:3},{value:"Callback function when the viewport changes",paraId:1,tocIndex:3},{value:"extraControlBtns",paraId:1,tocIndex:3},{value:"React.ReactNode[]",paraId:1,tocIndex:3},{value:"Additional control buttons",paraId:1,tocIndex:3},{value:"The Viewport object represents the coordinate system of a view, and includes the following properties:",paraId:2,tocIndex:4},{value:"Property",paraId:3,tocIndex:4},{value:"Type",paraId:3,tocIndex:4},{value:"Description",paraId:3,tocIndex:4},{value:"x",paraId:3,tocIndex:4},{value:"number",paraId:3,tocIndex:4},{value:"The x-coordinate of the top-left corner of the viewport",paraId:3,tocIndex:4},{value:"y",paraId:3,tocIndex:4},{value:"number",paraId:3,tocIndex:4},{value:"The y-coordinate of the top-left corner of the viewport",paraId:3,tocIndex:4},{value:"zoom",paraId:3,tocIndex:4},{value:"number",paraId:3,tocIndex:4},{value:"The zoom ratio of the viewport",paraId:3,tocIndex:4}]},84672:function(o,n){n.Z=`import { FreeCanvas } from '@ant-design/pro-editor';
import { Button } from 'antd';

export default () => (
  <div style={{ height: '100vh' }}>
    <FreeCanvas extraControlBtns={[<Button key="extra">\u81EA\u5B9A\u4E49</Button>]}>
      <Button>\u6309\u94AE</Button>
    </FreeCanvas>
  </div>
);
`}}]);
